### ISSUE TITLE
Possible Manjaro XFCE sleep issue

### ISSUE THREAD

**Issue by DanielOaks** [Shells-com/linux-scripts#54]
User reported on discord that when viewing their Manjaro shell, they got prompted with the login screen, and they think they're using XFCE. We'll take a look at this and do some testing to make sure Manjaro XFCE is being prevented from sleeping / etc properly.

**Comment by zgrimshell** [comment]
@DanielOaks once you get time to test it, please add more info to the issue.

* Once you reinstall into Manjaro XFCE, does it autologin?
*  Does it go into sleep after some time in idle?
* What is the output of logs, most notably the Xorg one?

**Comment by DanielOaks** [comment]
I've been trying this out through the day and haven't been able to reproduce it, so I'll close this issue for now. I'll keep an eye on things and see if any other users report this, and if they do I'll get more specific info from them and submit a new issue (thanks for that list, will do those if I run into this in future).
