### ISSUE TITLE
Xubuntu logout button isn't disabled

### ISSUE THREAD

**Issue by DanielOaks** [Shells-com/linux-scripts#60]
When you click the logout button on Xubuntu 20.04 LTS, it takes you back to a login screen. While you can hit enter to log back in again, we should match the behaviour of other XFCE images and automatically log the user back in without any input.

**Comment by zgrimshell** [comment]
This is an upstream bug, Xfce doesn't have the ability to disable logout though I think they started working of it after many years :)

**Comment by DanielOaks** [comment]
Hmm, while 341fe9d76505ebc92d9ea3350d47a4961e083aa6 _does_ make the user log back in after they've clicked the logout button - but it also makes the initial login on machine boot not work properly. I'd suggest reverting that commit and catting the line in [this answer](https://unix.stackexchange.com/a/593923) to the end of lightdm.conf.d/70-xubuntu.conf

I've tested and with `autologin-user-timeout=0` and the `session-cleanup-script` line linked above, both boot and logout work as expected (by automatically logging the user back in).

**Comment by zgrimshell** [comment]
https://github.com/Shells-com/linux-scripts/commit/5eb3d8384d599a0959824160fa1b282083c7df37 fixes it
