### ISSUE TITLE
Debian Buster GNOME desktop issues

### ISSUE THREAD

**Issue by DanielOaks** [Shells-com/linux-scripts#62]
There's a few issues with this image currently, so I'll collect them together here.

-----

Sound is muted by default when it shouldn't be.

-----

When resizing the screen, almost all of the time we end up with a segment of torn/incorrectly-rendered screen on the right and bottom of the display. It feels like the screen's being resized to be a bit smaller than the actual width of the browser window, and what's shown outside is just weird overdraw. Here's an example:
![image (1)](https://user-images.githubusercontent.com/251281/122345310-0ff43b00-cf8b-11eb-9d28-b6f9fd43e726.png)
(from discussion with the team, this is likely because wayland doesn't play nicely with spice)
(this screenshot takes up the entire size of the browser window)

-----

If the machine is restarted with `sudo shutdown now`, it stops and can be started again without issue. However, if the machine is rebooted with `sudo reboot`, then the machine seems to reboot into a strange zoomed-in mode where the entire display is something like 64x64 stretched pixels with a black background and the cursor in the top left. Here's an example of what this looks like:
![image (3)](https://user-images.githubusercontent.com/251281/122345401-2bf7dc80-cf8b-11eb-95f6-c32454da1b11.png)
(this happens before the screen gets resized to the proper browser window resolution, so the cursor is in the top left of the 4x3 screen size).

-----

This one probably isn't an issue of the desktop in particular, but it takes a very long time to boot in (minutes). I'm not sure whether this may be related to the screen issues or it's just because I'm using a heavier image on a smaller shell, but figured I'd mention it anyway.

**Comment by zgrimshell** [comment]
https://github.com/Shells-com/linux-scripts/commit/de967535ebe260da383a0ce27ec5312e1b80b240 partially fixed (the sound is fixed). The other issue likely comes because Spice and Wayland don't work well with each other, maybe forcing Debian into X session might be a viable solution here.

**Comment by DanielOaks** [comment]
Sound is now OK. Curiously the reboot issue is also resolved (that may be something to keep an eye on in future, may be inconsistent).

Regarding the screen tearing, we get the same on all images using Wayland so that seems like that's it. Should we create separate issues specifically about XFCE and Wayland screen size/tearing, and then close this one?

**Comment by zgrimshell** [comment]
This should be fully fixed now by reverting it to Xorg session
