### ISSUE TITLE
Ubuntu Hirsuite 21.04 suspends badly

### ISSUE THREAD

**Issue by DanielOaks** [Shells-com/linux-scripts#63]
The Suspend button can be pressed. After doing this, the shell is put into a state where it stops responding entirely (mouse/keyboard doesn't bring it back), and restarting the web viewer just results in a _"Connecting..."_ screen forever. Manually stopping and starting the shell fixes it, but that's a bit extreme. This issue isn't fixed by disabling the 'lock screen on suspend' option in the settings.

**Comment by zgrimshell** [comment]
Fixed in https://github.com/Shells-com/linux-scripts/commit/95cb03582c15313455f07274186f5976462251e9
