### ISSUE TITLE
Manjaro GNOME doesn't hide the Suspend, Log Out, etc buttons

### ISSUE THREAD

**Issue by DanielOaks** [Shells-com/linux-scripts#65]
Our other distributions that use GNOME, these buttons are all hidden. We should try to hide all these buttons on the Manjaro image as well, keep things clean and consistent and all.

**Comment by zgrimshell** [comment]
We now allow logout, restart but still disable suspend, sleep and hibernate - that said, this is fixed for current Manjaro GNOME.
